### ISSUE TITLE
Zeichen für Zeilenumbruch

### ISSUE THREAD

**Issue by michull** [ics-tools/ics.tools#11]
**Fehler**
Die Zeilen werden nicht mit CRLF, sondern nur mit LF abgegrenzt.

**Quelle**
https://datatracker.ietf.org/doc/html/rfc5545#section-3.1

**Gelieferte Daten (Hex Darstellung)**
0x42, 0x45, 0x47, 0x49, 0x4E, 0x3A, 0x56, 0x43, 0x41, 0x4C, 0x45, 0x4E, 0x44, 0x41, 0x52, 0x0A, 
0x56, 0x45, 0x52, 0x53, 0x49, 0x4F, 0x4E, 0x3A, 0x32, 0x2E, 0x30, 0x0A, 0x50, 0x52, 0x4F, 0x44, 

**Erwartete Daten (Hex Darstellung)**
0x42, 0x45, 0x47, 0x49, 0x4E, 0x3A, 0x56, 0x43, 0x41, 0x4C, 0x45, 0x4E, 0x44, 0x41, 0x52, 0x0D, 0x0A, 
0x56, 0x45, 0x52, 0x53, 0x49, 0x4F, 0x4E, 0x3A, 0x32, 0x2E, 0x30, 0x0D, 0x0A, 0x50, 0x52, 0x4F, 0x44, 

**Weiter Hinweise**
Es gibt einen Validator:
https://icalendar.org/validator.html?url=https://ics.tools/Feiertage/bayern.ics

**Comment by Skillkiller** [comment]
Hallo @michull,
Vielen Dank für deine Meldung. Ich habe mich mit dem Thema vor einer Weile bereits auseinandergesetzt. Dachte eigentlich ich hatte es behoben. Das Problem war das Git die Zeilenenden automatisch ersetzt beim commiten und pullen.

Den Validator kannte ich gar nicht. Hat beim Debuggen sehr geholfen. Dieser zeigt nun auch keine weiteren Fehler oder Warnungen an.

**Comment by michull** [comment]
Servus,
Danke für die schnelle Anpassung.
Viele Grüße Michael
