### ISSUE TITLE
Berlin: Einmaliger Feiertag am 8. Mai 2025

### ISSUE THREAD

**Issue by SVNKoch** [ics-tools/ics.tools#13]
fehlender Feiertag 08.05.2025 Berlin
Tag der Befreiung

https://www.berlin.de/aktuelles/9188766-958090-einmaliger-feiertag-am-8-mai-2025.html

(äquivalent zum bestehenden Feiertag Tag der Befreiung 08.05.2020 in Berlin)

**Comment by Skillkiller** [comment]
Vielen Dank für den Hinweis. Ich werde es entsprechend hinzufügen.
