### ISSUE TITLE
keine Einträge mehr in Thunderbird

### ISSUE THREAD

**Issue by ghost** [ics-tools/ics.tools#8]
**Beschreibe den Fehler**
Es werden keine Einträge mehr von abonnierten ics.tools-Kalendern in Thunderbird angezeigt. Einträge anderer abonnierter Kalender werden angezeigt. Ein Leeren des Kalender-Caches und eine erneute Synchronisation der ics.tools-Kalender beheben das Problem nicht.

**Welche Events sind betroffen**
alle

**Erwartete Daten**
alle

**Weiter Hinweise**
Thunderbird 115.4.1

**Comment by Skillkiller** [comment]
Hallo,
Danke für eine Meldung. Mir ist das bisher nicht aufgefallen weil mein Kalenderprogramm den Fehler unterdrückt aber auch nicht mehr entsprechend aktualisiert. Ich habe auch schon das Problem gefunden. Das Problem hat etwas einer Bibliothek zutun welche die ICS Datei nicht mehr ordentlich speichert. Ich habe einen entsprechenden Report ics-py/ics-py#405 erstellt und werde mich gucken wie ich Formattierung wieder hinbekommen.
